version: '3.8'

services:
  eureka-server-1:
    build:
      context: .
      dockerfile: dockerfile-eureka
    image: eureka-server:latest
    environment:
      SERVER_PORT: 7001
      EUREKA_INSTANCE_HOSTNAME: eureka_one
      EUREKA_CLIENT_SERVICE_URL: http://eureka-server-2:7002/eureka
    ports:
      - 7001:7001
    networks:
      - eureka-network

  eureka-server-2:
    build:
      context: .
      dockerfile: dockerfile-eureka
    image: eureka-server:latest
    environment:
      SERVER_PORT: 7002
      EUREKA_INSTANCE_HOSTNAME: eureka_two
      EUREKA_CLIENT_SERVICE_URL: http://eureka-server-1:7001/eureka
    ports:
      - 7002:7002
    networks:
      - eureka-network

  rabbit-mq-1:
    image: rabbitmq:3.9.29-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      eureka-network:

  message-provider-1:
    image: message-provider:latest
    environment:
      SERVER_PORT: 8090
      RABBITMQ_HOST: rabbit-mq-1
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${rabbit_mq_account}
      RABBITMQ_PASSWORD: ${rabbit_mq_p6d}
      CUSTOM_BINDING_NAME: my-message
      EUREKA_CLIENT_SERVICE_URL: http://eureka-server-1:7001/eureka, http://eureka-server-2:7002/eureka
      EUREKA_INSTANCE_ID: message-provider_8090
    ports:
      - 8090:8090
    networks:
      eureka-network:
    depends_on:
      - rabbit-mq-1
      - eureka-server-1
      - eureka-server-2

  message-consumer-1:
    image: message-consumer:latest
    environment:
      SERVER_PORT: 8091
      RABBITMQ_HOST: rabbit-mq-1
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${rabbit_mq_account}
      RABBITMQ_PASSWORD: ${rabbit_mq_p6d}
      RECEIVE_DESTINATION: my-message
      RECEIVE_GROUP: group-X
      EUREKA_CLIENT_SERVICE_URL: http://eureka-server-1:7001/eureka, http://eureka-server-2:7002/eureka
      EUREKA_INSTANCE_ID: message-consumer_8091
    ports:
      - 8091:8091
    networks:
      eureka-network:
    depends_on:
      - rabbit-mq-1
      - eureka-server-1
      - eureka-server-2

  message-consumer-2:
    image: message-consumer:latest
    environment:
      SERVER_PORT: 8092
      RABBITMQ_HOST: rabbit-mq-1
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${rabbit_mq_account}
      RABBITMQ_PASSWORD: ${rabbit_mq_p6d}
      RECEIVE_DESTINATION: my-message
      RECEIVE_GROUP: group-X
      EUREKA_CLIENT_SERVICE_URL: http://eureka-server-1:7001/eureka, http://eureka-server-2:7002/eureka
      EUREKA_INSTANCE_ID: message-consumer_8092
    ports:
      - 8092:8092
    networks:
      eureka-network:
    depends_on:
      - rabbit-mq-1
      - eureka-server-1
      - eureka-server-2

networks:
  eureka-network: