FROM eclipse-temurin:17.0.4.1_1-jre-alpine
COPY ./provider-payment-zookeeper/build/libs/provider-payment-zookeeper.jar .
EXPOSE 8084
ENV SERVER_PORT=8084
CMD ["java", "-jar", "provider-payment-zookeeper.jar"]